### ISSUE TITLE
Request feature: add button Detail

### ISSUE THREAD

**Issue by webserveis** [stkent/bugshaker-android#110]
It would be interesting in the error dialog, to choose optional to see the detail of the error report in a friendly way, possibility to copy part of the info and from there to be able to share it, whatsapp, telegram, email etc ....

Similar https://github.com/ajitsing/Sherlock

**Comment by stkent** [comment]
Are you specifically asking about crashes, or just about alternate ways to share the bug report information? The former I doubt will make it in to this library; the latter well might.

**Comment by webserveis** [comment]
I ask about alternative ways to view the error report

Upload a stream image for the proposal
![crash_report_features](https://cloud.githubusercontent.com/assets/2223709/25526579/7c6f65d0-2c14-11e7-8728-b38a37f5563d.jpg)

**Comment by stkent** [comment]
Ah gotcha... yeah, that's probably a bit beyond the scope of this particular project at the moment. Thanks for the suggestion!
