### ISSUE TITLE
BugShaker logo banner text is blurred

### ISSUE THREAD

**Issue by stkent** [stkent/bugshaker-android#33]
The original asset seems to have soft edges. I don't think this is obvious enough to be by design? cc @davidklaw for thoughts:

> <img width="463" alt="screen shot 2016-01-15 at 8 59 46 pm" src="https://cloud.githubusercontent.com/assets/6463980/12369747/2c18b40c-bbcb-11e5-8e47-d84b81c90196.png">

**Comment by davidklaw** [comment]
The image I used was designed for non-retina and probably doesn't scale well. I suppose we'll give 2x a shot (it looks clearer in my branch) but I don't know how to juggle retina and non-retina like I normally would with a regular web app.

**Comment by stkent** [comment]
That looks much sharper to me (on a retina screen)!

**Comment by stkent** [comment]
Resolved by #35
