### ISSUE TITLE
Add ability to trigger the report flow manually

### ISSUE THREAD

**Issue by mkpazon** [stkent/bugshaker-android#94]
I hope you can add an option that instead of listening to shake, manually trigger the bug reporting mechanism.

**Comment by stkent** [comment]
Thanks for the suggestion! Are you thinking that the manual trigger would be enabled in addition to the usual shake detection, or that it would replace the shake detection?

**Comment by mkpazon** [comment]
I am thinking that there should be 2 ways to trigger a bug report wherein one is not required for the other to work. I should be able to report a bug manually (clicking a button) without being forced to listen to a shake and vice versa. Or I can do both.

**Comment by stkent** [comment]
Ok, I'll think about this one. Probably won't get to it in the next few weeks, however.

**Comment by mkpazon** [comment]
Just realized that I can call `hearShake()` directly to trigger the bug reporting manually.

**Comment by stkent** [comment]
Ah, yes, of course! Does that fulfill your requirements, or would it still be preferable to be able to disable the automatic shake detection also?

**Comment by stkent** [comment]
I'm going to close this issue as declined; if users want to use the workaround above, that's fine, but I don't want to support disabling shake detection.
