### ISSUE TITLE
Specify email body

### ISSUE THREAD

**Issue by yukuku** [stkent/bugshaker-android#97]
Why can I specify the email subject but not the email body?

For example I want the reporter (internal QA team) to tell me how the app should behave, not just that "this screen has a problem!" so I want to say something on the email body.

Should we have a method `setEmailBody` on the builder?

**Comment by stkent** [comment]
Hi! Your QA team should already have the opportunity to supply custom notes in the email body before it is sent. Check out the screenshot below. It shows the default email content and state, with the cursor positioned below all the automatically-added device info ready for your testers or users to enter more detailed report notes!

Hopefully this covers your use-case, please reply to this comment if not :-)

![compose_screenshot](https://cloud.githubusercontent.com/assets/6463980/16192728/f61c78fc-36b8-11e6-94de-58772874aa2f.png)
